<template>
  <v-card
    class="pa-1"
    rounded="pill"
    height="fit-content"
  >
    <v-btn
      @click=""
      size="small"
      variant="text"
      icon="mdi-emoticon-happy-outline"
      class="pa-2"
    />
    <v-btn
      @click=""
      size="small"
      variant="text"
      icon="mdi-pencil"
      class="pa-2"
    />
  </v-card>
</template>
